# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemSettingService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='value',
            field=models.CharField(max_length=200),
        ),
    ]
