# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('customer_identifier', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('personal_identifier', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
