# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_identifier',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
