# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typeService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='resource_key',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='resource_key',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
