# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
