# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaService', '0002_media_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='seq',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
