# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaService', '0004_auto_20160425_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='seq',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
