# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerService', '0002_auto_20160425_2016'),
        ('mediaService', '0005_auto_20160425_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='customerService.Customer'),
        ),
    ]
