# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediaService', '0007_auto_20160504_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='customerService.Customer'),
        ),
    ]
