# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaService', '0008_auto_20160504_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='rented_date',
            field=models.DateField(null=True),
        ),
    ]
